# Generated by Django 5.2 on 2025-09-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('revenue_growth', models.FloatField(blank=True, null=True)),
                ('profit_margin', models.FloatField(blank=True, null=True)),
                ('burn_rate', models.FloatField(blank=True, null=True)),
                ('runway_months', models.FloatField(blank=True, null=True)),
                ('risk_flag', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
