# Generated by Django 5.2.6 on 2025-09-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='risk_flag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
