# Generated by Django 5.2.6 on 2025-09-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0002_alter_financialreport_risk_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='risk_flag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
