# Generated by Django 5.2 on 2025-09-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0003_alter_financialreport_risk_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='title',
            field=models.CharField(default='Untitled Report', max_length=255),
        ),
    ]
