# Generated by Django 5.2 on 2025-09-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0004_financialreport_size_financialreport_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='cash_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='total_expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='total_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='total_revenue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
