# Generated by Django 5.2 on 2025-09-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0005_financialreport_cash_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialreport',
            name='runway_months',
        ),
        migrations.AddField(
            model_name='financialreport',
            name='runway',
            field=models.FloatField(blank=True, help_text='Months of runway', null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='burn_rate',
            field=models.FloatField(blank=True, help_text='Monthly outflow in $', null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='profit_margin',
            field=models.FloatField(blank=True, help_text='Percentage value (e.g., 15 for 15%)', null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='revenue_growth',
            field=models.FloatField(blank=True, help_text='Percentage value (e.g., 20 for 20%)', null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='risk_flag',
            field=models.CharField(blank=True, choices=[('High Risk', 'High Risk'), ('Moderate/OK', 'Moderate/OK'), ('Low/Healthy', 'Low/Healthy')], max_length=50, null=True),
        ),
    ]
