# Generated by Django 5.2 on 2025-09-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0006_remove_financialreport_runway_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='runway_months',
            field=models.FloatField(blank=True, help_text='Months of runway', null=True),
        ),
    ]
