# Generated by Django 5.2.6 on 2025-09-17 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0008_financialgoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialreport',
            name='runway',
        ),
        migrations.AddField(
            model_name='financialreport',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='title',
            field=models.CharField(blank=True, default='Untitled Report', max_length=255, null=True),
        ),
    ]
